### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by khoahoc0508** [philipwfowler/snpit#14]
Please hekp to install. Thanks!
Terminal print:
$ make install
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
rm -fr .pytest_cache
rm -f .coverage
[ ! -d /home/trungvn90/Desktop/WGS/snpit/.venv ] || rm -rf /home/trungvn90/Desktop/WGS/snpit/.venv
mkdir -p /home/trungvn90/Desktop/WGS/snpit/.venv
python3 -m venv /home/trungvn90/Desktop/WGS/snpit/.venv
/home/trungvn90/Desktop/WGS/snpit/.venv/bin/python3 -m pip install --upgrade pip
Requirement already satisfied: pip in ./.venv/lib/python3.9/site-packages (22.0.4)
/home/trungvn90/Desktop/WGS/snpit/.venv/bin/python3 -m pip install /home/trungvn90/Desktop/WGS/snpit
Processing /home/trungvn90/Desktop/WGS/snpit
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [75 lines of output]
            checking for gcc... gcc
            checking whether the C compiler works... yes
            checking for C compiler default output file name... a.out
            checking for suffix of executables...
            checking whether we are cross compiling... no
            checking for suffix of object files... o
            checking whether we are using the GNU C compiler... yes
            checking whether gcc accepts -g... yes
            checking for gcc option to accept ISO C89... none needed
            checking for ranlib... ranlib
            checking for grep that handles long lines and -e... /usr/bin/grep
            checking for C compiler warning flags... -Wall
            checking for special C compiler options needed for large files... no
            checking for _FILE_OFFSET_BITS value needed for large files... no
            checking for _LARGEFILE_SOURCE value needed for large files... no
            checking shared library type for unknown-Linux... plain .so
            checking how to run the C preprocessor... gcc -E
            checking for egrep... /usr/bin/grep -E
            checking for ANSI C header files... yes
            checking for sys/types.h... yes
            checking for sys/stat.h... yes
            checking for stdlib.h... yes
            checking for string.h... yes
            checking for memory.h... yes
            checking for strings.h... yes
            checking for inttypes.h... yes
            checking for stdint.h... yes
            checking for unistd.h... yes
            checking for stdlib.h... (cached) yes
            checking for unistd.h... (cached) yes
            checking for sys/param.h... yes
            checking for getpagesize... yes
            checking for working mmap... yes
            checking for gmtime_r... yes
            checking for fsync... yes
            checking for drand48... yes
            checking whether fdatasync is declared... yes
            checking for fdatasync... yes
            checking for library containing log... -lm
            checking for zlib.h... yes
            checking for inflate in -lz... yes
            checking for library containing recv... none required
            checking for bzlib.h... yes
            checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
            checking for lzma.h... yes
            checking for lzma_easy_buffer_encode in -llzma... yes
            checking for libdeflate.h... no
            checking for libdeflate_deflate_compress in -ldeflate... no
            checking for curl_easy_pause in -lcurl... yes
            checking for CCHmac... no
            checking for library containing HMAC... no
            configure: WARNING: S3 support not enabled: requires SSL development files
            checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
            configure: creating ./config.status
            config.status: creating config.mk
            config.status: creating htslib.pc.tmp
            config.status: creating config.h
            make[1]: ./version.sh: Command not found
            make[1]: ./version.sh: Command not found
            error in pysam setup command: use_2to3 is invalid.
            # pysam: no cython available - using pre-compiled C
            # pysam: htslib mode is shared
            # pysam: HTSLIB_CONFIGURE_OPTIONS=None
            # pysam: htslib configure options: --enable-libcurl
            # pysam: htslib_config LDFLAGS=
            # pysam: htslib_config LIBHTS_OBJS=kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o hfile_libcurl.o hfile_gcs.o
            # pysam: htslib_config LIBS=-llzma -lbz2 -lz -lm -lcurl
            # pysam: htslib_config PLATFORM=default
            # pysam: config_option: ENABLE_PLUGINS=0
            # pysam: config_option: HAVE_COMMONCRYPTO=0
            # pysam: config_option: HAVE_GMTIME_R=1
            # pysam: config_option: HAVE_HMAC=0
            # pysam: config_option: HAVE_IRODS=0
            # pysam: config_option: HAVE_LIBCURL=1
            # pysam: config_option: HAVE_MMAP=1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/home/trungvn90/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/trungvn90/Desktop/WGS/snpit/.venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpamx1d8a9', '--quiet', 'pysam==0.15.2']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/trungvn90/Desktop/WGS/snpit/setup.py", line 4, in <module>
          setup()
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/trungvn90/Desktop/WGS/snpit/.venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpamx1d8a9', '--quiet', 'pysam==0.15.2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:102: install] Error 1

**Comment by mbhall88** [comment]
Hmmm. This might be to do with your version of python not being compatible with an older version of pysam.

Could you try changing all of the pysam versions in these lines https://github.com/philipwfowler/snpit/blob/9c20838772d4cb5726627385a9bb193434caf11a/setup.cfg#L24-L29 to the most recent version `pysam ==0.19`?

**Comment by khoahoc0508** [comment]
It works, thank you! But unfortunately i can not input pair-end FASTQ file. It said that only VCF and FASTA file allowed.
snpit --i ../../PBS/WTCHG_918772_70015073_1.fastq.gz -i ../../PBS/WTCHG_918772_70015073_2.fastq.gz -o lineage.tsv
Traceback (most recent call last):
  File "/home/trungvn90/Desktop/WGS/snpit/.venv/bin/snpit", line 33, in <module>
    sys.exit(load_entry_point('snpit==1.0.0', 'console_scripts', 'snpit')())
  File "/home/trungvn90/Desktop/WGS/snpit/.venv/lib/python3.9/site-packages/snpit/__main__.py", line 22, in main
    raise Exception(
Exception: Only VCF or FASTA files are allowed as input (may be compressed)

**Comment by mbhall88** [comment]
Yes. The expectation for input is a VCF from your fastq files, or an assembly in FASTA format.

**Comment by mbhall88** [comment]
@khoahoc0508 You can use https://github.com/Mykrobe-tools/mykrobe to get lineage directly from fastq
