### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by tseemann** [philipwfowler/snpit#9]
![image](https://user-images.githubusercontent.com/453972/70183066-3059fd00-1739-11ea-97dd-0d7db5d02519.png)

**Comment by mbhall88** [comment]
@philipwfowler I can't make that change as I don't own the repo. I guess the following is probably sufficient?
> Whole-genome SNP based identification of members of the Mycobacterium tuberculosis complex.

**Comment by philipwfowler** [comment]
Added description suggested by @mbhall88.
